### ISSUE TITLE
Including JWT in Requests

### ISSUE THREAD

**Issue by Disquietude** [hatchways/world-messenger#12]
There are several ways to include a JWT in a request and extract them in PassportJS. Which should we use for this project?

**Comment by Harukine** [comment]
I think just adding the token to the Header would be good
example

curl -X GET \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTM0OTI1MTQwLCJleHAiOjE1MzUwMTE1NDB9.MIcWFBzAr5WVhbaSa1kd1_hmEZsepo8fXqotqvAerKI' \
  http://localhost:8000

**Comment by Harukine** [comment]
Please review my README in the server directory to see how I've implemented it, if any issues please state them here so we can work on a better solution!
